import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/common/Header";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/common/AppSidebar";
// import { Geist } from "next/font/google";
// import { cn } from "@/lib/utils";

// const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="min-h-screen">
        <SidebarProvider>
          <TooltipProvider>
            <AppSidebar />
            <div className="flex min-h-screen flex-1 flex-col">
              <Header />
              <main>{children}</main>
            </div>
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
